on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable, oldstable]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Test
      run: go test ./...
