on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [stable, oldstable]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
    - name: Test
      run: go test ./...
